### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by lebedov** [alykhantejani/nninit#3]
Given that it is derived from [nninit](https://github.com/Kaixhin/nninit), I'm assuming that the license is MIT; still, it would be advisable to include a license file in the repo.

**Comment by alykhantejani** [comment]
@lebedov good point, I will add a License file in the repo today.

FYI -  this will also be merged into pytorch/nn fairly soon so I assume people will use it directly from there (and it will have the PyTorch license).

**Comment by alykhantejani** [comment]
This has now been added, thanks for reporting!
