### ISSUE TITLE
usage problem

### ISSUE THREAD

**Issue by Liu0329** [alykhantejani/nninit#5]
Should we use it like:
w = torch.Tensor(3, 5)
nninit.uniform(w)
OR:
w = torch.Tensor(3, 5)
w = nninit.uniform(w)
I suppose they give the same results ? But your function always return values ...

**Comment by alykhantejani** [comment]
Hi @Liu0329,

both ways are fine, the reason the functions return the tensor too is so you could chain operations i.e. `nninit.uniform(w).add(5)`

As a side note, I highly recommend using the version of `nnint` that has been merged and is available in the latest pytorch release (http://pytorch.org/docs/master/nn.html#torch-nn-init) as this one is un-maintained in favor of that.

**Comment by Liu0329** [comment]
Thanks for the quick reply !
